<?php
/**
 * @file at_module.module
 *
 * @todo Detect Moodle session, auto create Drupal session, sync data if there's
 *  any changes.
 *
 * @todo On user login, update user data (First name, last name, …).
 * @todo Data change on Drupal, push changes to Moodle.
 */

class AT_Moodle {
    /**
     * @return Drupal\at_moodle\Services\User
     */
    public static function getServiceUser() {
        return at_container('at_moodle.user');
    }
}

/**
 * Implements hook_init()
 */
function at_moodle_init() {
    $auth = user_is_anonymous() && !filter_has_var(INPUT_GET, 'reload');
    $auth = $auth && ('user/logout' !== request_path());
    $auth = $auth && ($msid = at_moodle_session_id());

    if ($auth) {
        $s_user = AT_Moodle::getServiceUser();

        if ($muser = $s_user->getMoodleUser($msid)) {
                $duser = $s_user->createDrupalUser($muser);

            if (FALSE !== $s_user->createDrupalSession($duser)) {
                drupal_goto(request_path(), array('reload' => 1));
            }
        }
    }
}

/**
 * Get Moodle's session ID.
 */
function at_moodle_session_id() {
  $msname = variable_get('moodle_session_name', 'MoodleSession');

  if (filter_has_var(INPUT_COOKIE, $msname)) {
      return filter_input(INPUT_COOKIE, $msname);
  }

  return FALSE;
}
