<?php
/**
 * @file at_moodle.module
 *
 * @todo Detect Moodle session, auto create Drupal session, sync data if there's
 *  any changes.
 *
 * @todo On user login, update user data (First name, last name, …).
 * @todo Data change on Drupal, push changes to Moodle.
 *
 * User > External auth system
 *
 *  user_get_authmaps($authname)
 *      Discover which external authentication module(s) authenticated a username.
 *
 *  user_external_load($authname)
 *      Fetches a user object based on an external authentication source.
 *
 *  user_external_login_register($name, $module)
 *      Helper function for authentication modules. Either logs in or registers
 *      the current user, based on username. Either way, the global $user object
 *      is populated and login tasks are performed.
 */

require_once __DIR__ . '/at_moodle.hooks.inc';

class AT_Moodle {
    /**
     * @return Drupal\at_moodle\Services\User
     */
    public static function getServiceUser() {
        return at_container('at_moodle.user');
    }
}

/**
 * Get Moodle's session ID.
 */
function at_moodle_session_id() {
  $msname = variable_get('moodle_session_name', 'MoodleSession');

  if (filter_has_var(INPUT_COOKIE, $msname)) {
      return filter_input(INPUT_COOKIE, $msname);
  }

  return FALSE;
}
