<?php
/**
 * @file at_module.module
 *
 * @todo Detect Moodle session, auto create Drupal session, sync data if there's
 *  any changes.
 *
 * @todo On user login, update user data (First name, last name, …).
 * @todo Data change on Drupal, push changes to Moodle.
 */

class AT_Moodle {
    /**
     * @return Drupal\at_moodle\Services\User
     */
    public static function getServiceUser() {
        return at_container('at_moodle.user');
    }
}


/**
 * Get Moodle's session ID.
 */
function at_moodle_session_id() {
  $msname = variable_get('moodle_session_name', 'MoodleSession');

  if (filter_has_var(INPUT_COOKIE, $msname)) {
      return filter_input(INPUT_COOKIE, $msname);
  }

  return FALSE;
}
